gems: [bourbon, neat]

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

highlighter: pygments

# Site settings
title: Jeff See Designs
description: Agile, Resonsive, Manageable Web Tools

# Name of project on Github
baseurl: /

# Build settings
markdown: kramdown
