source 'https://rubygems.org'

gem 'bourbon'
gem 'coffee-script'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-haml'
gem 'neat'
gem 'sass'
gem 'uglifier'
gem 'font-awesome-sass', '~> 4.2.0'
gem 'nokogiri'
